export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const ADD_NEW_TWEET = 'ADD_NEW_TWEET';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const ADD_FOLLOWED_TWEET = 'ADD_FOLLOWED_TWEET';
export const REMOVE_FOLLOWED_TWEET = 'REMOVE_FOLLOWED_TWEET'